[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "freetype-dev", "harfbuzz", "ca-certificates", "ttf-dejavu"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build", "cd backend && npm install"]

[start]
cmd = "cd backend && npm start"
